### ISSUE TITLE
cannot find /usr/lib64/libtsan.so.2.0.0

### ISSUE THREAD

**Issue by gasche** [ocaml-multicore/ocaml-tsan#32]
Out of curiosity I decided to give https://github.com/ocaml/ocaml/pull/12114 a spin.

After checking the branch I ran `make distclean` and then `./configure --enable-tsan`, and it failed because it didn't find libunwind. I installed it, and now `./configure` works. Great!

But then `make -j` fails:

```
  MKEXE runtime/ocamlrun
/usr/bin/ld: cannot find /usr/lib64/libtsan.so.2.0.0
```

I would expect that `./configure` checks for the presence of this library, if `--enable-tsan` is given.

**Comment by OlivierNicole** [comment]
This is one we hadn’t seen yet. Thank you for this report. I infer from your message in another issue that you managed to install it in the end. May I ask what was missing?

For me and @fabbing TSan always came with the compiler and the compiler figured out where its library was.

**Comment by gasche** [comment]
> May I ask what was missing?

I had to install the `libtsan` package on my distribution (it's a Fedora 36). (It looks like it is using gcc with tsan, not clang.)

**Comment by OlivierNicole** [comment]
690c8ed89f21e29632b489991212280cde667be7 fixes this for @fabbing and me. Can you check on Fedora?

**Comment by gasche** [comment]
I checked and the commit works: if I don't have `libtsan` then configure fails, if I have `libtsan` the configure passes.
